version: '3'
services:
  spring_boot_com_mysql:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: spring_boot_com_mysql/api
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
    links:
      - db
  db:
    image: mysql:8.0.23
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=spring_boot_mysql
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql